version: 2
updates:
  # Manage Python dependencies
  - package-ecosystem: "pip"
    directory: "/"  # Root directory where `requirements.txt` is located
    schedule:
      interval: "weekly"  # Can be daily, weekly, or monthly
    open-pull-requests-limit: 5
    reviewers:
      - "your-github-username"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "example-package"  # Add packages to ignore if needed

  # Manage GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"  # Location of your GitHub Actions workflows
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    reviewers:
      - "your-github-username"
    labels:
      - "ci"
